### ISSUE TITLE
integration of "intensivregister" and especially the dynamic data development in the register

### ISSUE THREAD

**Issue by pflegende** [micb25/corona-jena#8]
may be that this suggestion exceeds the project target. But as an evident part of the covid19 data record it would be nice to integrate the "intensivregister" and especially the dynamic data development in the register. 
e.g, in thuringia is to see: some healthcare stakeholders dont bring the data also 2 weeks after the obligation "to bring".

The law "obligation to bring" in thuringia:
https://www.tmasgff.de/fileadmin/user_upload/Gesundheit/Dateien/COVID-19/3._ThuerSARS-CoV-2-EindmassnVO.pdf  i.V.m.
https://www.tmasgff.de/fileadmin/user_upload/Gesundheit/Dateien/COVID-19/20200407_Versorgungskonzept.pdf  i.V.m.
https://www.thueringen.de/mam/th7/tmsfg/gesundheit/krankenhauswesen/krankenhausplan_thueringen.pdf

Some comments to actual situation of implementation by obligation "to bring":
-> https://demenzpflaster.wordpress.com/2020/04/20/betteninventur-thueringen-17-04/
-> https://demenzpflaster.wordpress.com/2020/04/13/divi-intensivregister-betteninventur-in-thueringen/

The origin INTENSIVREGISTER:
https://www.intensivregister.de/#/intensivregister

The daily updated  JSON - API of INTENSIVREGISTER (state of Apr. 28th.):
https://interaktiv.morgenpost.de/corona-deutschland-intensiv-betten-monitor-krankenhaus-auslastung/data/intensivregister.json
https://www.intensivregister.de/api/public/intensivregister (raw JSON)

2 examples for parsing the API data (after dl):
jq '.data[] | select(.krankenhausStandort.bundesland == "THUERINGEN") | .meldezeitpunkt + " co= " + ( .faelleCovidAktuell | tostring ) + " " + .label + "   HighCare: " + .bettenStatus.statusHighCare'
jq '.data[] | select(.faelleCovidAktuell >= 10) | ( .faelleCovidAktuell | tostring ) + " ECMO: " + .bettenStatus.statusECMO + " " + .label'

example of result "select(.faelleCovidAktuell >= 20)"
http://ix.io/2k6p

the universe of INTENSIVREGISTER on GitHub:
https://github.com/search?q=intensivregister

Other interesting question:
following the INTENSIVREGISTER hospital names and postal adresses: 
-> investigation of the number of beds and also  more parameters by scraping some crawled sites like the homepages of the hospitals or some existing local overwiew sides where sometimes the numbers of beds are hided.

**Comment by micb25** [comment]
Hallo, 

vielen Dank für den Hinweis. Ein Crawler für die Daten existiert bereits ([https://github.com/micb25/corona-jena/blob/master/crawler/crawler_divi_th.py](https://github.com/micb25/corona-jena/blob/master/crawler/crawler_divi_th.py)). Allerdings werden die Daten momentan aus anderen Gründen nicht automatisiert erhoben:

"Wir weisen darauf hin, dass die Inhalte dieser Webseite als Datenbank nach dem Urheberrechtsgesetz geschützt sind. Verstöße hiergegen können kostenpflichtig zivilrechtlich sowie strafrechtlich geahndet werden. Bitte kontaktieren Sie uns, sofern Sie Inhalte dieser Seite verwenden möchten."

Eventuell muss ich dort noch einmal anfragen, aber ich kann mir nur sehr schwer vorstellen, dass ich die täglichen Daten hier im Github-Repository öffentlich sammeln darf.

Nachtrag: unter [https://www.quarks.de/gesundheit/medizin/so-ist-die-situation-auf-den-deutschen-intensivstationen/](https://www.quarks.de/gesundheit/medizin/so-ist-die-situation-auf-den-deutschen-intensivstationen/) finden sich schicke Grafiken auf Basis der Zahlen des DIVI-Intensivregisters, die ich heute gesehen habe.

**Comment by pflegende** [comment]
:) Thx!
Könnte aber sein, dass die damit gegen das thüringer Transparenzgesetz verstoßen, wenn das für mit Steuergeld geförderte Daten so locker festgestellt wird. Könnte natürlich andererseits sein, dass sich die dann wiederum auf die Meldedaten der thüringer Leistungsanbieter aka Krankenhäuser beschränken.   CU   
Selbsthilfegruppe pflegender Angehöriger
Demenz - Pflaster https://demenzpflaster.wordpress.com

(registriert bei KISS Erfurt Tel. 655-4204
https://www.erfurt.de/ef/de/rathaus/sv/aemter/stelle-241.htmc )

Zur anonymen Kontaktaufnahme:
https://www.afpk-erfurt.de/kontakt
(Bitte Kennwort "Demenzpflaster" verwenden.) 

Am 30-Apr-2020 02:02:25 +0200 schrieb notifications@github.com: 

Hallo, ein Crawler für die Daten existiert bereits. Allerdings werden die Daten momentan aus anderen Gründen nicht automatisiert erhoben: 

"Wir weisen darauf hin, dass die Inhalte dieser Webseite als Datenbank nach dem Urheberrechtsgesetz geschützt sind. Verstöße hiergegen können kostenpflichtig zivilrechtlich sowie strafrechtlich geahndet werden. Bitte kontaktieren Sie uns, sofern Sie Inhalte dieser Seite verwenden möchten."

**Comment by micb25** [comment]
Die Anfrage bei einem der wissenschaftlichen Leitern des DIVI-Intensivregister war erfolgreich. Die öffentlichen Zahlen aus der Tabelle unter [https://diviexchange.z6.web.core.windows.net/laendertabelle1.svg](https://diviexchange.z6.web.core.windows.net/laendertabelle1.svg) dürfen genutzt werden. Ein Scraper ist bereits geschrieben, Grafiken folgen noch.

**Comment by pflegende** [comment]
Micha, Micha, Micha ... das is ja ganz großartig.    Toll. Herzlichen Dank.   Ich habe immer noch keine richtige Erklärung für das anhaltende gap bei den Meldungen der Thüringer Krankenhäuser und Rehaeinrichtungen an das Intensivregister. Das TMASGFF ist angefragt, hat sich aber seit ca. 2 Wochen dazu noch nicht gemeldet. Ende April stand die Anzahl der gemeldeten Sätze bei 37, leicht verbessert gegenüber den lange Zeit nur 35, aber eigentlich sollten es gemäß der Übersicht des TAMSGFF über 50 sein.
Andererseits wäre das, sofern das TMASGFF selber, woher auch immer, noch den Überblick über die Ressourcen hat, für Thüringen im Katastrophenfall natürlich eine gewisse Reserve, zumal die anderen Bundesländer ja nicht diese Verpflichtung für Rehaeinrichtungen und Einrichtungen ohne Intensivbetten zur Meldungen haben und diese damit dort also überall ohnehin eine solche Reserve bilden. Die DE VO verpflichtet ja nur Krankenhäuser und nur welche mit Intensivbetten zur Meldung. Insofern hat sich der Freistaat ja auch "schlechter" gestellt indem er alle Betreiber zur Meldung ins Intensivregister verpflichtete. Sollte Dir diesbezüglich mal was unterkommen, was nach hilfreicher Info aussehen könnte, sind wir für eine Weiterleitung dankbar. Haben auch gerade Eure R0-Debatte gelesen. Wir sind weiter auf die Fortentwicklung des Projektes gespannt.   CU F 
Selbsthilfegruppe pflegender Angehöriger
Demenz - Pflaster https://pflegende.gitlab.io (unsere joomla site hat gerade jemand gekapert, ticket ist unterwegs)

(registriert bei KISS Erfurt Tel. 655-4204
https://www.erfurt.de/ef/de/rathaus/sv/aemter/stelle-241.htmc )

Zur anonymen Kontaktaufnahme:
https://www.afpk-erfurt.de/kontakt
(Bitte Kennwort "Demenzpflaster" verwenden.) 

Am 30-Apr-2020 14:55:07 +0200 schrieb notifications@github.com: 

Die Anfrage bei einem der wissenschaftlichen Leitern des DIVI-Intensivregister war erfolgreich. Die öffentlichen Zahlen aus der Tabelle unter https://diviexchange.z6.web.core.windows.net/laendertabelle1.svg dürfen genutzt werden. Ein Scraper ist bereits geschrieben, Grafiken folgen noch.
