### ISSUE TITLE
incorrect data entry for Jena, 2020-12-31 23:59

### ISSUE THREAD

**Issue by knarrff** [micb25/corona-jena#9]
The data for Jena, 2020-12-31 23:59 was entered as 2021-12-31 23:59. Those data are actually not yet inside the repo, but will be fetched using data/update_cases.sh (which is inside the repo) and produces a rather wrong https://michael-böhme.de/corona/plot3_Jena.png.

**Comment by jometzner** [comment]
Looks like the opendata portal from Jena is the root cause for this. The false timestamp `1640991599` is already in there.

https://opendata.jena.de/dataset/2cc7773d-beba-43ad-9808-a420a67ffcb3/resource/d3ba07b6-fb19-451b-b902-5b18d8e8cbad/download/corona_erkrankungen_jena.csv

**Comment by knarrff** [comment]
... and they seemed to have corrected it. I guess it's time to close this issue then. Thanks for your work btw.
